[workspace]
resolver = "2"
members = [
	"crates/algo_models",
	"crates/algo_models_ffi",
	"crates/ffi_macros",
	"crates/uniffi-bindgen", "tools/cargo-bin",
]

[workspace.metadata.bin]
polytest = { version = "0.3.0", locked = true }
