name: Python CI

on:
  push:
    paths:
      - crates/algo_models_ffi/**
      - creates/algo_models/**
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
    paths:
      - crates/algo_models_ffi/**
      - creates/algo_models/**
  workflow_dispatch:

permissions:
  contents: read

env:
  CRATE_PATH: crates/algo_models_ffi
  # Python >= 3.8 is needed to support manylinux_x_y tags (unless you want to manually update pip)
  # Python 3.10 was chosen because it is currently the most popular according to https://mayeut.github.io/manylinux-timeline/
  PYTHON_VERSION: '3.10'

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.target.runner }}
    strategy:
      matrix: 
        target:
          # name: The name of the target passed to cargo build
          # runner: The GitHub runner to use
          - name: x86_64-pc-windows-msvc
            runner: windows-latest
          - name: x86_64-apple-darwin
            runner: macos-13
          - name: aarch64-apple-darwin
            runner: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip' # caching pip dependencies
      - run: pip install maturin
      - name: Install python dependencies
        run: pip install -r ${{ env.CRATE_PATH }}/tests/py/requirements.txt
      - name: maturin build
        run: |
          cd ${{ env.CRATE_PATH }} 
          maturin build --release --target ${{ matrix.target.name }}
      - name: pytest
        run: |
          set -e
          pip install target/wheels/*.whl
          cd ${{ env.CRATE_PATH }}
          pytest

  linux_build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-22.04${{ matrix.arch == 'aarch64' && '-arm' || '' }}
    strategy:
      matrix:
        arch: [aarch64, x86_64, i686, ppc64le, s390x]
        libc: [gnu, musl]
        exclude:
          - arch: s390x
            libc: musl
          - arch: ppc64le
            libc: musl

    env:
      # See https://github.com/pypa/manylinux for more information on manylinux
      # Generally it's good to try to support the glibc version from two RHEL releases ago (roughly within EOM period)
      # The current RHEL release (as of 2/7/2025) is 9 and the glibc version from RHEL 7 was 2.17 (aka manylinux2014)
      MANYLINUX: ${{ matrix.libc == 'musl' && 'musllinux_1_2' || 'manylinux2014' }}
      TARGET: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.arch != 'aarch64' && matrix.arch != 'x86_64'
        uses: docker/setup-qemu-action@v3

      - name: Start Container
        env:
          container: quay.io/pypa/${{ env.MANYLINUX }}_${{ matrix.arch }}
        run: | 
          set -e
          docker pull ${{ env.container }}
          docker run --name build-container \
          -d \
          -v ${{ github.workspace }}:/workspace \
          -e CARGO_HOME="/usr/local" \
          ${{ env.container }}  \
          tail -f /dev/null

      - name: Install Rustup
        env:
          SCRIPT: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        run: docker exec build-container bash -c "$SCRIPT"

      - name: rustup target add
        env:
          SCRIPT: rustup target add ${{ env.TARGET }}
        run: docker exec build-container bash -c "$SCRIPT"

      - name: pip install maturin[patchelf]
        env:
          SCRIPT: python${{ env.PYTHON_VERSION }} -m pip install maturin[patchelf]
        run: docker exec build-container bash -c "$SCRIPT"

      - name: maturin build
        env:
          SCRIPT: |
            cd /workspace/${{ env.CRATE_PATH }}
            python${{ env.PYTHON_VERSION }} -m maturin build --release --target ${{ env.TARGET }} --compatibility ${{ env.MANYLINUX }}
        run: docker exec build-container bash -c "$SCRIPT"

      - name: pip install wheel
        env:
          SCRIPT: python${{ env.PYTHON_VERSION }} -m pip install /workspace/target/wheels/*.whl
        run: docker exec build-container bash -c "$SCRIPT"

      - name: pip install test requirements
        env:
          SCRIPT: python${{ env.PYTHON_VERSION }} -m pip install -r /workspace/${{ env.CRATE_PATH }}/tests/py/requirements.txt
        run: docker exec build-container bash -c "$SCRIPT"
      
      - name: pytest
        env:
          SCRIPT: |
            cd /workspace/${{ env.CRATE_PATH }}
            python${{ env.PYTHON_VERSION }} -m pytest
        run: docker exec build-container bash -c "$SCRIPT"
