name: Swift CI

on:
  push:
    paths:
      - crates/algo_models_ffi/**
      - crates/algo_models/**
      - dist/swift/**
      - "!*.md"
      - .github/workflows/swift_ci.yml
    branches:
      - main
      - master
    tags:
      - "*"
  pull_request:
    paths:
      - crates/algo_models_ffi/**
      - crates/algo_models/**
      - dist/swift/**
      - "!*.md"
      - .github/workflows/swift_ci.yml
  workflow_dispatch:

permissions:
  contents: read

env:
  CRATE: algo_models
  PACKAGE: AlgoModels

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: mac
    strategy:
      matrix:
        platform:
          - macOS
          # - watchOS
          # - tvOS
          - iOS
          - mac-catalyst
          # - visionOSos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios, x86_64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios, aarch64-apple-ios-macabi, x86_64-apple-ios-macabi, aarch64-apple-darwin, x86_64-apple-darwin
      - uses: actions/setup-python@v5
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"
      - name: Build Swift
        run: python -m dist.swift ${{ env.CRATE }}
      - uses: mxcl/xcodebuild@v3
        with:
          swift: ^6
          action: test
          platform: ${{ matrix.platform }}
          working-directory: dist/swift/${{ env.PACKAGE }}
