name: Swift CI

on:
  push:
    paths:
      - crates/algo_models_ffi/**
      - crates/algo_models/**
      - build/swift/**
      - "!*.md"
    branches:
      - main
      - master
    tags:
      - "*"
  pull_request:
    paths:
      - crates/algo_models_ffi/**
      - crates/algo_models/**
      - build/swift/**
      - "!*.md"
  workflow_dispatch:

permissions:
  contents: read

env:
  CRATE_PATH: crates/algo_models_ffi

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios, x86_64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios, aarch64-apple-ios-macabi, x86_64-apple-ios-macabi, aarch64-apple-darwin, x86_64-apple-darwin
      - uses: actions/setup-python@v5
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"
      - name: Build Swift
        run: python -m build.swift
      - name: Test Swift
        run: cd build/swift/AlgoModels && swift test
